### ISSUE TITLE
Cinnamon window-list icons are sometimes clipped

### ISSUE THREAD

**Issue by lss4** [B00merang-Project/Windows-3.11#2]
OS: Manjaro Cinnamon (latest)
Monitor: 3840x2160 with HiDPI Enabled
(NOTE: It's possible some issues I'm having only happens with HiDPI enabled)

As of most recent commits it's working good so far, with some issues:
1. The panel is set to a transparent background with black text, which may not cope well with a dark wallpaper, although this can be customized through editing cinnamon.css to match my need.
2. A black line appears on some windows that weren't maximized (using Nemo for example). When maximized the black line disappears. Also, it seems on such windows, the titlebar color is the same when the window is active or is inactive.
![image](https://user-images.githubusercontent.com/30771484/64071030-fd244f80-ccab-11e9-85ce-dcd978434724.png)
![image](https://user-images.githubusercontent.com/30771484/64071081-ddd9f200-ccac-11e9-9f48-6ad4f57fb225.png)

The issues are mostly about Cinnamon, although the experience has been improved to a point that's good enough since moving out of the original Redmond-Themes repository. I also have a system running this theme but on XFCE and without HiDPI, and the experience there is near perfect for the time being.

**Comment by Elbullazul** [comment]
thanks for pointing it out, will have a look as soon as possible.

**Comment by lss4** [comment]
By the way... it seems the icons for taskbar buttons are cropped under Cinnamon.
![image](https://user-images.githubusercontent.com/30771484/64268829-cbdda500-cf73-11e9-9761-ebfb794f8b49.png)
Not sure if this could be worked around with some CSS adjustments...

EDIT: Clicked "Close and Comment" by accident, sorry about that. :cat:

**Comment by lss4** [comment]
Seems setting `.window-list-item-box` could fix the cropped icons.
I give it a padding of 0px (from 2px) and a margin of 1px (from 5px), and now it looks much better.
![image](https://user-images.githubusercontent.com/30771484/64270513-99817700-cf76-11e9-85ba-9a2e6da4111a.png)

**Comment by Elbullazul** [comment]
848e3d1 fixes this
