### ISSUE TITLE
[XFCE] Clarifications needed on some changes since Redmond-Themes, for Windows 3.11 theme.

### ISSUE THREAD

**Issue by lss4** [B00merang-Project/Windows-3.11#3]
On XFCE, the panel buttons now look Windows 95-ish, while using the original version from Redmond-Themes the panel buttons looked okay.

Redmond-Themes master:
![image](https://user-images.githubusercontent.com/30771484/64084492-93b14900-cd5e-11e9-85d3-c020537387a4.png)

Current master:
![image](https://user-images.githubusercontent.com/30771484/64084416-e1798180-cd5d-11e9-849a-51477aed66e6.png)

On the other hand, it seems as of current master some layouts have been improved, and some menu buttons now have a hovering effect (using Thunar's back/forward buttons for example). Looking carefully, it appears the hovering effect's transitioning state looked similar to Windows 95's buttons, so not sure if this might be related to the button's appearance on the panel.

EDIT: Also, maybe related to the changes, the button edges are less rounded than before.

**Comment by Elbullazul** [comment]
It could indeed be related. They use a common widget code (button.flat) and I don't remember tweaking it accurately for this theme. Will have a look.

I believe I reduced button radius from 3px to 2px, so that may explain the reduced roundness. I'll have a look at the source material and update you on this

**Comment by lss4** [comment]
Also, with the latest version on this repo, I found that the buttons on some dialogs have some strange issues.

![image](https://user-images.githubusercontent.com/30771484/64136356-9164f280-ce23-11e9-8c4d-a18b492868aa.png)
Using Firefox's close dialog (when you have multiple tabs open) for example. There would be a thick black border (plus a rounded border inside, with white between the square and rounded edges) on the Close Tabs button, while for Cancel button, there would be slightly visible black square edges.

However, I'm unable to screenshot this dialog with the issue visible using xfce4-screenshooter, as the problem would not appear when the dialog/button is not in focus. You can test this with Firefox, as it's easily reproducible.

**Comment by lss4** [comment]
As of the most recent changes, the panel buttons look correct and no longer Windows 95-ish.
![Screenshot_2020-01-13_09-57-26](https://user-images.githubusercontent.com/30771484/72229651-33bf8e80-35eb-11ea-90fc-9e19af010a3b.png)

And for the bug with Firefox, this time I managed to get screenshots with the bug visible.

1. Close Tabs button in focus.
![Screenshot_2020-01-13_09-50-02](https://user-images.githubusercontent.com/30771484/72229518-35d51d80-35ea-11ea-9284-d362f30c9a0a.png)

2. Cancel button in focus.
![Screenshot_2020-01-13_09-52-42](https://user-images.githubusercontent.com/30771484/72229557-80ef3080-35ea-11ea-8674-27a86a5cf6f5.png)

Currently I only see the issue with Firefox and I haven't seen the issue appearing in other apps yet.

**Comment by Elbullazul** [comment]
I'll have a look at that firefox dialog button

**Comment by Elbullazul** [comment]
Ok, so recently got back to maintaining the themes, replicated the bug. Possibly caused by some difference in outline radius. Will try to correct

**Comment by Elbullazul** [comment]
781fd473bd19a5e02dec80d02f39f9c7299e880d fixes this

![image](https://user-images.githubusercontent.com/15310985/100400784-a419a780-3025-11eb-89bd-225ce9f57cc7.png)

**Comment by lss4** [comment]
Yes, can confirm the issue has been fixed. :+1:
